## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  server:
    requests:
      memory: 200Mi
      cpu: 100m
    limits:
      memory: 700Mi
  sentinel:
    requests:
      memory: 200Mi
      cpu: 100m
    limits:
      memory: 200Mi

## Node labels and tolerations for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#taints-and-tolerations-beta-feature
app: "redis"

tolerations: 
  - key: "mysql" 
    operator: "Equal"
    value: "exits"
    effect: "NoSchedule"
  - key: "redis" 
    operator: "Equal"
    value: "exits"
    effect: "NoSchedule"

## Redis image version
#redis_image: quay.io/smile/redis:4.0.6r2
redis_image: redis:3.2.9
## replicas number for each component
replicas:
  servers: 3
  sentinels: 3
